name: 0.1 - Copy Inf. templates 

env:
  AWS_REGION: 'eu-west-1'
  ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
  ZONE_NAME: ${{ secrets.HOSTED_ZONE_NAME }}
  CERT: ${{ secrets.WEB_CERT }}

on:
  push:
    branches: ['main']
    paths: ['infra/**']
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_EX }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_EX }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Create CloudFormation temp
        run: |
          sudo chmod +x ./infra/cloudformation/infra.sh && ./infra/cloudformation/infra.sh $ZONE_ID $ZONE_NAME $CERT

      - name: Copy infrastructure templates
        run: |
          aws s3 sync ./infra/cloudformation/ s3://project_name/cloudformation/