name: 1 - Create Inf. Stack

env:
  aws_env: 'dev'
  AWS_REGION: 'eu-west-1'


on:
  schedule:
    - cron: '50 05 * * 1-5'  # at 7:50 UTC on every day-of-week from Monday through Friday
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_EX }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_EX }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Create Mendix application stack
        run: |
          aws cloudformation create-stack \
          --stack-name project-resources \
          --template-url https://project-static-resources-${{ env.aws_env }}.s3.${{ env.AWS_REGION }}.amazonaws.com/cloudformation/infra.yml \
          --parameters ParameterKey=Environment,ParameterValue=${{ env.aws_env }}  \
          --capabilities CAPABILITY_IAM
          aws cloudformation wait stack-create-complete --stack-name project-resources